### PR TITLE
Test

### PR DESCRIPTION
**Pull request by UNiQ10**
Since soccerwindow2 is working fine and also because the --port flag of the monitor (start.py line 75) is for soccerwindow2 not rcssmonitor (it should be --server-port for rcssmonitor) it is better to switch to soccerwindow2

### CODE REVIEW

**Comment by mhauskn** [comment]
Thanks for the PR! It looks good :)

I'm going to change the flags a little bit so that a user can specify the number of offensive agents, defensive agents, offensive teammates, and defensive teammates. This way we can support both single-agent and multi-agent learning.

**Comment by UNiQ10** [comment]
Should we proceed with the multi agent setup

**Comment by mhauskn** [comment]
What more needs to be done for the multi-agent setup?

**Comment by UNiQ10** [comment]
What does the output of "features = hfo.getState()" (Line 23, HFO/example/hfo_example_agent.py) correspond to? I mean each value in the tuple correspond to in the state of the world.

**Comment by mhauskn** [comment]
They are documented in the manual. Please see https://github.com/mhauskn/HFO/blob/master/doc/manual.pdf

Notably missing from this set are features that tell the agent if it has the ball and/or the location of the ball. I suspect I should add these features.

**Comment by UNiQ10** [comment]
Yes, please add those.

**Comment by mhauskn** [comment]
Will add them today.

**Comment by mhauskn** [comment]
I've updated the manual and high level feature set to include ball-related features. Please do a pull to get the latest.

**Pull request merged**
