### PR TITLE
Added support for random offense player on ball

### PR DESCRIPTION
**Pull request by UNiQ10**

### CODE REVIEW

**Comment by mhauskn** [comment]
See my comment on the other PR.

**Comment by mhauskn** [comment]
Can you change the offense-on-ball flag to use the same semantics as it has in the rcssserver? I mean, rather than being a bool, it should take an int for the player number to give the ball to.

**Comment by UNiQ10** [comment]
Sorry for taking so long. Please check if the PR is fine.

**Comment by mhauskn** [comment]
Thanks, the PR looks good. I made just a few comments on the PR in the
rcssserver. Once both are ready, I will merge them both.

**Comment by watts4speed** [comment]
Ok cool!  I've verified that I build HFO/master and the game demo works
correctly.  I'm assuming everything in master should work.  It was the
header files that were not working for me off master.  Let me know if I
should use the branch instead.

**Comment by watts4speed** [comment]
Oops, wrong email sorry :-(

**Pull request merged**
